version: '3.0'

services:
  db-course:
    container_name: db_course
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-course
      POSTGRES_USER: ismael
      POSTGRES_PASSWORD: Test123
    ports:
      - "5434:5434"
    command:
      -p 5434

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  db-keycloak:
    container_name: db_keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-keycloak
      POSTGRES_USER: ismael
      POSTGRES_PASSWORD: Test123
    ports:
      - "5435:5435"
    command:
      -p 5435

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: [ "start-dev" ]
    ports:
      - "8181:8181"
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: ismael
      DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181


