spring:
  application:
    name: fl-mcsv-notification

  datasource:
    url: jdbc:postgresql://localhost:5434/db-course
    username: ismael
    password: Test123
  mail:
    host: smtp.gmail.com
    port: 587
    username: ismaeltrocha@gmail.com
    password: yagtjxoslseihrcc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: fl-mcsv-notification
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

