server:
  port: 9000

spring:
  application:
    name: fl-mcsv-gateway
  cloud:
    gateway:
      routes:
        - id: FL-MCSV-COURSE
          uri: lb://FL-MCSV-COURSE
          predicates:
            - Path=/api/course/**

        - id: FL-MCSV-COURSE_CONTENT
          uri: lb://FL-MCSV-COURSE
          predicates:
            - Path=/api/course-content/**

        - id: FL-MCSV-MEDIA
          uri: lb://FL-MCSV-MEDIA
          predicates:
            - Path=/api/file-upload/**
            - Method=POST

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
