server:
  port: 9000

spring:
  application:
    name: fl-mcsv-gateway
  cloud:
    gateway:
      routes:
        - id: fl-mcsv-course
          uri: lb://fl-mcsv-course
          predicates:
            -Path=/api/**

        - id: fl-mcsv-media
          uri: lb://fl-mcsv-media
          predicates:
            -Path=/api/file-upload/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}