server:
  port: 0
spring:
  application:
    name: fl-mcsv-student
  datasource:
    url: jdbc:postgresql://localhost:5436/db_enrolls
    username: ismael
    password: Test123
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com:
      netflix:
        discovery: DEBUG
        eureka: DEBUG