server:
  port: 8081
spring:
  application:
    name: fl-mcsv-course
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:15260/railway
    username: postgres
    password: veptjqHqvLXaLTdjxfirILaEMgRKyLqS
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}