server:
  port: 8081
spring:
  application:
    name: fl-mcsv-course
  datasource:
    url: jdbc:postgresql://localhost:5434/db-course
    username: ismael
    password: Test123
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}